version: '3'
services:
  backend:
    build:
      context: ./pokemon-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./pokemon-UI
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend

